### PR TITLE
FRONT-17 Make Frontend V2 Mobile Responsive

### PR DESCRIPTION
**Pull request by JacobRoe**
The frontend is not adjusting it's content according to the viewport size. As a first step, the DashboardScreen should now be usable on mobile devices. The account menu becomes a drawer on smaller screens.

For convenience reasons I used inline styling but will switch to a proper way later on, together with component refactoring efforts.

### To-Do
- [x] 1. Make the remaining screens and components mobile-friendly
- [ ] ~2. Refactor several components by extracting them into smaller (and/or generalized) ones~
- [ ] ~3. Make better use of the material-ui theming capabilities~

### Appendix
| DashboardScreen             |  Drawer | 
:-------------------------:|:-------------------------:
|

### Updates
- **29.05.2020 12:52** Removed tasks 2 & 3 because they are only nice to have but not required for the Story FRONT-17, also see https://github.com/remedyMatch/rm-frontend/pull/51#issuecomment-635812517

### CODE REVIEW

**Comment by hauptmedia** [comment]
Nice, i think it would make sense to directly merge it because everything is better than the current "completely broken on mobile" state?

**Comment by JacobRoe** [comment]
> Nice, i think it would make sense to directly merge it because everything is better than the current "completely broken on mobile" state?

I updated the remaining screens. It's not ideal but usable now for every screen size. It can be reviewed and merged.

**Comment by hauptmedia** [comment]
Can you fix the merge conflict which resulted from merging the maps view? thanks

**Comment by JacobRoe** [comment]
@hauptmedia Done.

**Pull request merged**
